# key-db is a multi-threaded redis clone

services:
  key-db:
    image: eqalpha/keydb:alpine
    ports:
      - "6379:6379"
    volumes:
      - key-db:/data
    environment:
      - REDIS_PASSWORD=123456
      - REDIS_PORT=6379

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - psql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

volumes:
  key-db:
    driver: local
  psql:
    driver: local



